In [121]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import seaborn as sns
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, models, Input
from sklearn.metrics import classification_report, confusion_matrix
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD,Adam

In [122]:
df = pd.read_csv(r'C:\ai_class\week12\seeds_dataset.txt',
                delim_whitespace=True, # 구분자 화이트스페이스스
                names=['A','P','C','LK','WK','A_Coef','LKG','target'])  # 컬럼명 직접 지정

df


C:\Users\이민규\AppData\Local\Temp\ipykernel_14768\248706818.py:1: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(r'C:\ai_class\week12\seeds_dataset.txt',


A      P       C     LK     WK  A_Coef    LKG  target
0    15.26  14.84  0.8710  5.763  3.312   2.221  5.220       1
1    14.88  14.57  0.8811  5.554  3.333   1.018  4.956       1
2    14.29  14.09  0.9050  5.291  3.337   2.699  4.825       1
3    13.84  13.94  0.8955  5.324  3.379   2.259  4.805       1
4    16.14  14.99  0.9034  5.658  3.562   1.355  5.175       1
..     ...    ...     ...    ...    ...     ...    ...     ...
205  12.19  13.20  0.8783  5.137  2.981   3.631  4.870       3
206  11.23  12.88  0.8511  5.140  2.795   4.325  5.003       3
207  13.20  13.66  0.8883  5.236  3.232   8.315  5.056       3
208  11.84  13.21  0.8521  5.175  2.836   3.598  5.044       3
209  12.30  13.34  0.8684  5.243  2.974   5.637  5.063       3

[210 rows x 8 columns]

In [123]:
df.columns

Index(['A', 'P', 'C', 'LK', 'WK', 'A_Coef', 'LKG', 'target'], dtype='object')

In [124]:
df['target'].value_counts()

target
1    70
2    70
3    70
Name: count, dtype: int64

In [125]:
df.isnull().sum()

A         0
P         0
C         0
LK        0
WK        0
A_Coef    0
LKG       0
target    0
dtype: int64

In [126]:
X = df.drop('target', axis=1)
y=df['target']
y.value_counts()

target
1    70
2    70
3    70
Name: count, dtype: int64

In [127]:
Y = pd.get_dummies(y).values # 원-핫 인코딩
Y

array([[ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ T

In [128]:
scaler = StandardScaler()
X = scaler.fit_transform(X)
X

array([[ 1.42097769e-01,  2.15462437e-01,  6.06017918e-05, ...,
         1.41701823e-01, -9.86151745e-01, -3.83577423e-01],
       [ 1.11880257e-02,  8.22375713e-03,  4.28515270e-01, ...,
         1.97432229e-01, -1.78816620e+00, -9.22013487e-01],
       [-1.92066576e-01, -3.60200562e-01,  1.44238325e+00, ...,
         2.08047544e-01, -6.67479334e-01, -1.18919199e+00],
       ...,
       [-5.67570840e-01, -6.90247348e-01,  7.33948301e-01, ...,
        -7.06044846e-02,  3.07658816e+00, -7.18060432e-01],
       [-1.03608992e+00, -1.03564515e+00, -8.01701104e-01, ...,
        -1.12152071e+00, -6.81351965e-02, -7.42534799e-01],
       [-8.77620233e-01, -9.35863561e-01, -1.10234659e-01, ...,
        -7.55292327e-01,  1.29122264e+00, -7.03783718e-01]])

In [129]:
# X = X.values # 딥러닝 입력을 위해 numpy로 변환

In [130]:
X

array([[ 1.42097769e-01,  2.15462437e-01,  6.06017918e-05, ...,
         1.41701823e-01, -9.86151745e-01, -3.83577423e-01],
       [ 1.11880257e-02,  8.22375713e-03,  4.28515270e-01, ...,
         1.97432229e-01, -1.78816620e+00, -9.22013487e-01],
       [-1.92066576e-01, -3.60200562e-01,  1.44238325e+00, ...,
         2.08047544e-01, -6.67479334e-01, -1.18919199e+00],
       ...,
       [-5.67570840e-01, -6.90247348e-01,  7.33948301e-01, ...,
        -7.06044846e-02,  3.07658816e+00, -7.18060432e-01],
       [-1.03608992e+00, -1.03564515e+00, -8.01701104e-01, ...,
        -1.12152071e+00, -6.81351965e-02, -7.42534799e-01],
       [-8.77620233e-01, -9.35863561e-01, -1.10234659e-01, ...,
        -7.55292327e-01,  1.29122264e+00, -7.03783718e-01]])

In [131]:
X_train_val, X_test, y_train_val, y_test = train_test_split(X, Y, test_size=0.15, random_state=42)
X_train, X_val, y_train, y_val = train_test_split(X_train_val, y_train_val, test_size=0.15/0.85, random_state=42)

In [132]:
# 컬럼갯수 확인
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(146, 7) (146, 3)
(32, 7) (32, 3)


In [133]:
num_classes = y_train.shape[1]
input_shape = X_train.shape[1:]

In [134]:
def train_and_evaluate(model, name):
    model.compile(
        optimizer='adam',
        loss='categorical_crossentropy',
        metrics=['accuracy']
    )
    print(f"\n=== Training {name} ===")
    history = model.fit(
        X_train, y_train,
        epochs=30,
        batch_size=32,
        validation_data=(X_val, y_val),
        verbose=1
    )
    print(f"\n=== Evaluating {name} on Test Set ===")
    test_loss, test_acc = model.evaluate(X_test, y_test, verbose=0)
    print(f"{name} Test loss: {test_loss:.4f}, Test accuracy: {test_acc:.4f}")

    y_pred = model.predict(X_test)
    y_test_class = np.argmax(y_test, axis=1)
    y_pred_class = np.argmax(y_pred, axis=1)

    print(f"\n{name} Classification Report:")
    print(classification_report(y_test_class, y_pred_class))
    print(f"{name} Confusion Matrix:")
    print(confusion_matrix(y_test_class, y_pred_class))
    return history

In [135]:
# 1) Sequential API with .add()
seq_model = models.Sequential()
seq_model.add(layers.InputLayer(input_shape=input_shape))
seq_model.add(layers.Dense(7, activation='relu'))          # 입력층
seq_model.add(layers.Dense(14, activation='relu'))         # 히든층
seq_model.add(layers.Dense(28, activation='relu'))         # 히든층
seq_model.add(layers.Dense(14, activation='relu'))         # 히든층
seq_model.add(layers.Dense(7, activation='relu'))          # 히든층
seq_model.add(layers.Dense(num_classes, activation='softmax'))  # 출력층
train_and_evaluate(seq_model, 'Sequential')

c:\anaconda\Lib\site-packages\keras\src\layers\core\input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



=== Training Sequential ===
Epoch 1/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.3191 - loss: 1.0739 - val_accuracy: 0.1875 - val_loss: 1.0938
Epoch 2/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.3318 - loss: 1.0459 - val_accuracy: 0.1875 - val_loss: 1.0763
Epoch 3/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.3700 - loss: 1.0063 - val_accuracy: 0.2188 - val_loss: 1.0614
Epoch 4/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.3702 - loss: 0.9957 - val_accuracy: 0.2188 - val_loss: 1.0449
Epoch 5/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.4655 - loss: 0.9639 - val_accuracy: 0.2812 - val_loss: 1.0303
Epoch 6/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5504 - loss: 0.9606 - val_accuracy: 0.2812 - val_loss: 1.0155
Epoch 7/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6687 - loss: 0.9080 - val_accuracy: 0.3125 - val_loss: 1.0007
Epoch 8/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6456 - loss: 0.8990 - val_accurac

In [136]:
# 2) Functional API
inputs = Input(shape=input_shape)
x = layers.Dense(7, activation='relu')(inputs)       # 입력층
x = layers.Dense(14, activation='relu')(x)
x = layers.Dense(28, activation='relu')(x)
x = layers.Dense(14, activation='relu')(x)
x = layers.Dense(7, activation='relu')(x)
outputs = layers.Dense(num_classes, activation='softmax')(x)  # 출력층
func_model = models.Model(inputs, outputs, name='functional_model')
train_and_evaluate(func_model, 'Functional')



=== Training Functional ===
Epoch 1/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.4167 - loss: 1.0906 - val_accuracy: 0.5000 - val_loss: 1.0845
Epoch 2/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4417 - loss: 1.0671 - val_accuracy: 0.5625 - val_loss: 1.0690
Epoch 3/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4524 - loss: 1.0598 - val_accuracy: 0.5938 - val_loss: 1.0514
Epoch 4/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5194 - loss: 1.0391 - val_accuracy: 0.6250 - val_loss: 1.0322
Epoch 5/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5555 - loss: 1.0256 - val_accuracy: 0.7188 - val_loss: 1.0102
Epoch 6/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5792 - loss: 1.0017 - val_accuracy: 0.7500 - val_loss: 0.9859
Epoch 7/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6406 - loss: 0.9649 - val_accuracy: 0.7500 - val_loss: 0.9586
Epoch 8/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6707 - loss: 0.9474 - val_accurac

In [137]:
# 3) Subclassing Model
class SubclassedModel(models.Model):
    def __init__(self, num_classes):
        super(SubclassedModel, self).__init__()
        self.dense1 = layers.Dense(7, activation='relu')
        self.dense2 = layers.Dense(14, activation='relu')
        self.dense3 = layers.Dense(28, activation='relu')
        self.dense4 = layers.Dense(14, activation='relu')
        self.dense5 = layers.Dense(7, activation='relu')
        self.dense6 = layers.Dense(num_classes, activation='softmax')

    def call(self, inputs, training=False):
        x = self.dense1(inputs)
        x = self.dense2(x)
        x = self.dense3(x)
        x = self.dense4(x)
        x = self.dense5(x)
        return self.dense6(x)

sub_model = SubclassedModel(num_classes)
sub_model.build((None,) + input_shape)
train_and_evaluate(sub_model, 'Subclassed')


=== Training Subclassed ===
Epoch 1/30


c:\anaconda\Lib\site-packages\keras\src\layers\layer.py:395: UserWarning: `build()` was called on layer 'subclassed_model_2', however the layer does not have a `build()` method implemented and it looks like it has unbuilt state. This will cause the layer to be marked as built, despite not being actually built, which may cause failures down the line. Make sure to implement a proper `build()` method.
  warnings.warn(


5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.3533 - loss: 1.0988 - val_accuracy: 0.3438 - val_loss: 1.0756
Epoch 2/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.3446 - loss: 1.0684 - val_accuracy: 0.3438 - val_loss: 1.0470
Epoch 3/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.3537 - loss: 1.0387 - val_accuracy: 0.3438 - val_loss: 1.0254
Epoch 4/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.3741 - loss: 1.0104 - val_accuracy: 0.3438 - val_loss: 1.0108
Epoch 5/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.2869 - loss: 1.0017 - val_accuracy: 0.3438 - val_loss: 0.9939
Epoch 6/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.3229 - loss: 0.9756 - val_accuracy: 0.3438 - val_loss: 0.9773
Epoch 7/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.3442 - loss: 0.9244 - val_accuracy: 0.3438 - val_loss: 0.9585
Epoch 8/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.2891 - loss: 0.9216 - val_accuracy: 0.4062 - val_loss: 0.9389
Epoch 9/30
